"""initial schema

Revision ID: e135b136955a
Revises: 
Create Date: 2026-08-31 22:30:20.149685

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e135b136955a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('channel', sa.Enum('meta', 'google', 'youtube', 'linkedin', 'organic', 'referral', 'other', name='channeltype'), nullable=False),
    sa.Column('target_audience', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('utm_source', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('utm_medium', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('utm_campaign', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('utm_content', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('utm_term', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('budget', sa.Numeric(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_verifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('otp_code_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_identifier'), 'otp_verifications', ['identifier'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.Enum('tech_training', 'interview_prep', 'placement_support', 'soft_skills', 'complete_package', name='productcode'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('role', sa.Enum('admin', 'marketing', 'trainer', 'mentor', 'support', 'placement', name='staffrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('trainer_id', sa.Uuid(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('planned', 'active', 'completed', 'cancelled', name='batchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_postings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('role_title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('job_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('landing_page_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('new', 'contacted', 'converted', 'dropped', name='leadstatus'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('converted_candidate_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['converted_candidate_id'], ['candidates.id'], name='fk_leads_converted_candidate_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_code', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('classification', sa.Enum('beginner', 'starter', 'pro', name='candidateclassification'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_candidates_candidate_code'), 'candidates', ['candidate_code'], unique=True)
    op.create_table('modules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('unlock_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_course_id'), 'modules', ['course_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('business_problem', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expected_outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('free_assessment', 'ai_mock_diagnostic', 'module_quiz', 'formal_readiness', name='assessmenttype'), nullable=False),
    sa.Column('related_module_id', sa.Uuid(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('max_score', sa.Numeric(), nullable=True),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('classification', sa.Enum('job_ready', 'targeted_brushup', 'structured_preparation', name='readinessclassification'), nullable=True),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['related_module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_candidate_id'), 'assessments', ['candidate_id'], unique=False)
    op.create_table('automation_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_type', sa.Enum('registration', 'after_session_1', 'after_session_2', 'after_session_3', 'plus_24h', 'plus_72h', 'plus_7d', name='automationtrigger'), nullable=False),
    sa.Column('channel', sa.Enum('whatsapp', 'email', 'sms', name='automationchannel'), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_events_candidate_id'), 'automation_events', ['candidate_id'], unique=False)
    op.create_table('funnel_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lead_id', sa.Uuid(), nullable=True),
    sa.Column('candidate_id', sa.Uuid(), nullable=True),
    sa.Column('campaign_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnel_events_event_type'), 'funnel_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_funnel_events_occurred_at'), 'funnel_events', ['occurred_at'], unique=False)
    op.create_table('job_matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('job_posting_id', sa.Uuid(), nullable=False),
    sa.Column('match_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_matches_candidate_id'), 'job_matches', ['candidate_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('module_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('type', sa.Enum('video', 'trainer_explanation', 'lab', 'notes', 'assignment', 'quiz', 'practical', 'interview_questions', 'ai_doubt_assistant', name='lessontype'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('video_asset_id', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_module_id'), 'lessons', ['module_id'], unique=False)
    op.create_table('mock_interviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('ai_practice', 'expert_mock', name='mocktype'), nullable=False),
    sa.Column('mock_number', sa.Integer(), nullable=True),
    sa.Column('interviewer_id', sa.Uuid(), nullable=True),
    sa.Column('is_final_mock', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conducted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mock_interviews_candidate_id'), 'mock_interviews', ['candidate_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('razorpay_order_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('razorpay_signature', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('status', sa.Enum('created', 'authorized', 'paid', 'failed', 'refunded', name='paymentstatus'), nullable=False),
    sa.Column('invoice_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_index(op.f('ix_payments_candidate_id'), 'payments', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=False)
    op.create_table('placement_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('job_posting_id', sa.Uuid(), nullable=True),
    sa.Column('stage', sa.Enum('profile_review', 'preparation_pending', 'job_ready', 'resume_approved', 'jobs_matched', 'submitted', 'interview_scheduled', 'feedback_awaited', 'selected', 'offer_received', 'joined', name='pipelinestage'), nullable=False),
    sa.Column('channel', sa.Enum('portal', 'hr', 'direct_vendor', 'client', name='submissionchannel'), nullable=True),
    sa.Column('blocker', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('next_action', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_posting_id'], ['job_postings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_submissions_candidate_id'), 'placement_submissions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_placement_submissions_stage'), 'placement_submissions', ['stage'], unique=False)
    op.create_table('project_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('submission_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_review_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_review_score', sa.Numeric(), nullable=True),
    sa.Column('mentor_id', sa.Uuid(), nullable=True),
    sa.Column('mentor_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'ai_reviewed', 'mentor_approved', 'rejected', name='submissionstatus'), nullable=False),
    sa.Column('final_presentation_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_submissions_candidate_id'), 'project_submissions', ['candidate_id'], unique=False)
    op.create_table('readiness_gates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('projects_complete', sa.Boolean(), nullable=False),
    sa.Column('mocks_complete', sa.Boolean(), nullable=False),
    sa.Column('formal_score', sa.Numeric(), nullable=True),
    sa.Column('final_mock_score', sa.Numeric(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'qualified', 'approved_for_placement', name='gatestatus'), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readiness_gates_candidate_id'), 'readiness_gates', ['candidate_id'], unique=False)
    op.create_table('registrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('education', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('graduation_year', sa.Integer(), nullable=True),
    sa.Column('experience_years', sa.Numeric(), nullable=True),
    sa.Column('current_skills', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('earlier_training', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('career_gap_months', sa.Integer(), nullable=True),
    sa.Column('target_role', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('coding_preference', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('resume_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('learning_availability', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('chosen_schedule', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('campaign_source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_source_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registrations_candidate_id'), 'registrations', ['candidate_id'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('ats_score', sa.Numeric(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_candidate_id'), 'resumes', ['candidate_id'], unique=False)
    op.create_table('support_tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('lms', 'payment', 'schedule', 'trainer', 'assignment', 'project', 'interview', 'resume', 'mock', 'placement', 'technical', name='ticketcategory'), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'escalated', name='ticketstatus'), nullable=False),
    sa.Column('assigned_to', sa.Uuid(), nullable=True),
    sa.Column('sla_due_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_tickets_candidate_id'), 'support_tickets', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_status'), 'support_tickets', ['status'], unique=False)
    op.create_table('trial_progress',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'missed', name='trialsessionstatus'), nullable=False),
    sa.Column('lab_completed', sa.Boolean(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_progress_candidate_id'), 'trial_progress', ['candidate_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'completed', name='activitystatus'), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_candidate_id'), 'activities', ['candidate_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('instructions', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('due_offset_days', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=True),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('support_owner_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', 'dropped', name='enrollmentstatus'), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['support_owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollments_batch_id'), 'enrollments', ['batch_id'], unique=False)
    op.create_index(op.f('ix_enrollments_candidate_id'), 'enrollments', ['candidate_id'], unique=False)
    op.create_table('interview_rounds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('submission_id', sa.Uuid(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['placement_submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_rounds_submission_id'), 'interview_rounds', ['submission_id'], unique=False)
    op.create_table('payment_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('price_at_purchase', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_items_payment_id'), 'payment_items', ['payment_id'], unique=False)
    op.create_table('placement_recovery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('rejection_count', sa.Integer(), nullable=False),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('brushup_start', sa.Date(), nullable=True),
    sa.Column('brushup_end', sa.Date(), nullable=True),
    sa.Column('repeat_mock_id', sa.Uuid(), nullable=True),
    sa.Column('resumed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused_for_brushup', 'resumed', 'closed', name='recoverystatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['repeat_mock_id'], ['mock_interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_placement_recovery_candidate_id'), 'placement_recovery', ['candidate_id'], unique=False)
    op.create_table('ticket_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('author_candidate_id', sa.Uuid(), nullable=True),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticket_comments_ticket_id'), 'ticket_comments', ['ticket_id'], unique=False)
    op.create_table('assignment_submissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('submission_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('submitted', 'ai_reviewed', 'mentor_approved', 'rejected', name='submissionstatus'), nullable=False),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignment_submissions_candidate_id'), 'assignment_submissions', ['candidate_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignment_submissions_candidate_id'), table_name='assignment_submissions')
    op.drop_table('assignment_submissions')
    op.drop_index(op.f('ix_ticket_comments_ticket_id'), table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_index(op.f('ix_placement_recovery_candidate_id'), table_name='placement_recovery')
    op.drop_table('placement_recovery')
    op.drop_index(op.f('ix_payment_items_payment_id'), table_name='payment_items')
    op.drop_table('payment_items')
    op.drop_index(op.f('ix_interview_rounds_submission_id'), table_name='interview_rounds')
    op.drop_table('interview_rounds')
    op.drop_index(op.f('ix_enrollments_candidate_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_batch_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_activities_candidate_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_trial_progress_candidate_id'), table_name='trial_progress')
    op.drop_table('trial_progress')
    op.drop_index(op.f('ix_support_tickets_status'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_candidate_id'), table_name='support_tickets')
    op.drop_table('support_tickets')
    op.drop_index(op.f('ix_resumes_candidate_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_registrations_candidate_id'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_index(op.f('ix_readiness_gates_candidate_id'), table_name='readiness_gates')
    op.drop_table('readiness_gates')
    op.drop_index(op.f('ix_project_submissions_candidate_id'), table_name='project_submissions')
    op.drop_table('project_submissions')
    op.drop_index(op.f('ix_placement_submissions_stage'), table_name='placement_submissions')
    op.drop_index(op.f('ix_placement_submissions_candidate_id'), table_name='placement_submissions')
    op.drop_table('placement_submissions')
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_candidate_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_mock_interviews_candidate_id'), table_name='mock_interviews')
    op.drop_table('mock_interviews')
    op.drop_index(op.f('ix_lessons_module_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_job_matches_candidate_id'), table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index(op.f('ix_funnel_events_occurred_at'), table_name='funnel_events')
    op.drop_index(op.f('ix_funnel_events_event_type'), table_name='funnel_events')
    op.drop_table('funnel_events')
    op.drop_index(op.f('ix_automation_events_candidate_id'), table_name='automation_events')
    op.drop_table('automation_events')
    op.drop_index(op.f('ix_assessments_candidate_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_table('projects')
    op.drop_index(op.f('ix_modules_course_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_candidates_candidate_code'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    op.drop_table('job_postings')
    op.drop_table('courses')
    op.drop_table('batches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_index(op.f('ix_otp_verifications_identifier'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
